pipeline {
    agent any
    stages {
        stage('Build'){
            steps {
                echo 'Building the project'
            }
        }
        stage('Test'){
            steps {
                echo 'Testing the code'
            }
        }
        stage('Deploy'){
            steps{
                echo 'Deploying to server'
            }
        }
    }
}