pipeline {
    agent any
     stages {
         stage('Clone') {
            steps {
                echo 'Cloning repository...'
            }
         }
        stage('Build'){
            steps {
                //map jenkins secret ID to a temporary environment variable
                withCredentials([string(credentialsId: 'OPENAI_API_KEY', variable: 'OPENAI_API_KEY')]) {
                bat '''
                @echo off
                echo 'Checking Directory'
                dir /b
                echo 'Entering sub-folder'
                cd QUESTDigital-beta_version_lite
                echo 'running script'
                set SDL_VIDEODRIVER=dummy
                set SDL_AUDIODRIVER=dummy
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
                python stefie.py
                '''
                }
            }
        }
        stage('Test'){
            steps {
                echo 'Testing the code'
            }
        }
        stage('Deploy'){
            steps{
                echo 'Deploying to server'
            }
        }
    }
}